### ISSUE TITLE
doesn't work in google: www.google.com

### ISSUE THREAD

**Issue by bujisama** [Kiuryy/Bookmark_Sidebar#66] opened 2018-12-07 19:20 UTC
in other website I can normally click the left side of the window to open the bookmark sidebar, but when I open "www.google.com", I try to open it in the same way,  it just doesn't work.

**Comment by Kiuryy** [comment] 2018-12-07 22:35
There are many reasons why the sidebar is not working on a website. I cannot reproduce problems which google.com on my systems, so it's hard to tell why you experience problems there. The only thing I can do is suggest you some things you can try out:

I most cased, the sidebar initialisation failed, which can be fixed by reloading the website again. Another thing you can try is restarting the browser, or, disable the extension, restart the browser, enable the extension again and open google.com afterwards.

If you have other extensions installed, these may interfere, too. You can also check, whether there are any errors reported in the dev console, pointing to a problem with the extension. Maybe there is something to find the reason for the issue on google.com on your system.

**Closed** 2018-12-23 10:15 UTC
Labels: Bug, Needs more infos
